### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by diego-maravankin** [cottonbeckfield/python-csr#14]
Hello! I needed a script for this and bumped into your code. 

I just ported csrgen to Python 3, and added the option to add IP Address SANS to the CSR.

I'd like to create a pull request, but could not create a new branch and push my changes. Can you help me with that?

Thanks!
Diego

**Comment by cottonbeckfield** [comment]
Hi there,

You should fork the repository and then create a pull request. 

Thanks,
Cotton

**Comment by diego-maravankin** [comment]
Just opened the PR. I will go ahead and close this issue.
