### ISSUE TITLE
Improve prompts and handle empty user input in prompts 

### ISSUE THREAD

**Issue by hackerpants** [cottonbeckfield/python-csr#2]
I think it would be good if the prompts showed example input, similar to the `openssl`

```
Enter your country (2 letter code) [US]:
```

also, if you don't enter something when [prompted](https://github.com/cjcotton/python-csr/blob/b70aeee9e2588bd6a970bf27fafaadc3142d5299/csrgen.py#L24) current the script errors,

```
OU = raw_input("Enter your organizational unit: ")
...
req.get_subject().organizationalUnitName = OU
```

**Comment by cottonbeckfield** [comment]
Sure, in the next update I'll include this for ease.

**Comment by cottonbeckfield** [comment]
Update Text to reflect OpenSSL + adding in validation.
