### ISSUE TITLE
Looks like program is incomplete

### ISSUE THREAD

**Issue by bmbermn** [cottonbeckfield/python-csr#9]
[root@ip-10-0-0-225 python-csr]# ./csr_tools/csrgen.py -f sample.yaml -u csr.yaml
Enter your Common Name (eg, DNS name) [ip-10-0-0-225]:
Traceback (most recent call last):
  File "./csr_tools/csrgen.py", line 406, in <module>
    main(sys.argv)
  File "./csr_tools/csrgen.py", line 395, in main
    cert.generateFromFile(args.file)
AttributeError: Certificate instance has no attribute 'generateFromFile'

**Comment by cottonbeckfield** [comment]
Yeeeeep. Super broken, awesome. 

Welp, generateFromFile no longer exists and was replaced by a function called _parseYAML so I'm going to guess this happened when the last branch was pulled into master. I'll look at putting this in a virtualenv and splicing together some of the work that has been done and fixing it.

**Comment by cottonbeckfield** [comment]
This should be fixed with my last merge. The CLI portion was working, but now it works if you give it a file similar to sample.yaml. You can also provided a csr-sample.yml and a sample.yml to have everything get filled out.
